title:            Sidali HALLAK(alias Bigali)
description:      mobile and web developer addicted to caffeine and tv series.
disqus_shortname: bigaligithubio
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://bigali.github.io

# Owner/author information
owner:
  name:           Sidali HALLAK
  avatar:         avatar.jpg
  bio:            "mobile and web developer, last year student in Higher national school of computer science in Algeria."
  email:          s_hallak@esi.dz
  # Social networking links used in footer. Update and remove as you like.
  twitter:  https://twitter.com/sidalihallak      
  facebook: https://www.facebook.com/bigaliz
  github:   https://github.com/bigali      
  stackexchange: https://stackexchange.com/users/3070611/sidali-hallak 
  linkedin:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +https://www.linkedin.com/profile/view?id=183337120

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Africa/Algiers	
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]